version: '3'
services:
  nginx:
    build:
      context: back
      dockerfile: nginx.docker
    restart: always
    volumes:
      - ../back/:/app:ro
    environment:
      TZ: "Europe/Moscow"
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - network

  php-fpm:
    restart: always
    build:
      context: back
      dockerfile: php-fpm.docker
    user: "1000:1000"
    volumes:
      - ../back/my_project:/app:www
      - ./back/usr/local/etc/php/custom.d:/usr/local/etc/php/custom.d:ro
      - ./data/logs/php-fpm:/logs:www
    expose:
      - 9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: "Europe/Moscow"
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      PHP_IDE_CONFIG: serverName=docker-${COMPOSE_PROJECT_NAME}
      PHP_INI_SCAN_DIR: ":/usr/local/etc/php/custom.d"
      REDIS_HOST: redis
    networks:
      - network

  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=my_password
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: my_password
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: my_password
      ME_CONFIG_MONGODB_URL: mongodb://admin:my_password@mongo:27017/

networks:
  network:
    driver: bridge
    ipam:
      driver: default

